# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r5va2A6SifPU0RFov7qVStLO4yHSvzow
"""

import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

import io

data = pd.read_csv(io.BytesIO(uploaded['iris.csv']))

data.head()

data['species'].value_counts()

import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt

sns.pairplot(data, hue='species', markers='+')
plt.show()

data.hist()
plt.show()

data.describe

x = data.iloc[:,0:4]

x.head()

y = data.iloc[:,4]

y.head()

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

x_train.shape

x_test.shape

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

sc.fit(x_train)
x_train= sc.transform(x_train)
x_test = sc.transform(x_test)

from sklearn.svm import SVC

svm = SVC(kernel='rbf', random_state=0, gamma=.10, C=1.0)

svm.fit(x_train,y_train)

from sklearn.model_selection import cross_val_score

score = svm.score(x_test,y_test)

score

from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier()
random_forest.fit(x_train,y_train)
random_forest.score(x_test,y_test)

random_forest.score(x_test,y_test)